### ISSUE TITLE
captcha not working

### ISSUE THREAD

**Issue by freddii** [freetuxtv/freetuxtv-webtv-manager#2]
![captcha](https://user-images.githubusercontent.com/7213207/98821815-50f20300-2430-11eb-8a82-ebd16826df71.png)

maybe try alternatives:
https://github.com/Gregwar/Captcha
https://github.com/dapphp/securimage
https://github.com/ZYSzys/awesome-captcha

**Comment by SaiyanRiku** [comment]
It was just a recent migration problem. It should be fixed now by commit daa5de8b21f02c3711872eab1dba00e48b5c803c.
